// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("Categoria")]
    public partial class Categoria
    {
        public Categoria()
        {
            Prodottos = new HashSet<Prodotto>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }

        [InverseProperty("IDCategoriaNavigation")]
        public virtual ICollection<Prodotto> Prodottos { get; set; }
    }
}