// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("Corriere")]
    public partial class Corriere
    {
        public Corriere()
        {
            Ordines = new HashSet<Ordine>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }

        [InverseProperty("IDCorriereNavigation")]
        public virtual ICollection<Ordine> Ordines { get; set; }
    }
}