// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("Ordiniprodotti")]
    [Index("ID", Name = "IX_Ordiniprodotti")]
    public partial class Ordiniprodotti
    {
        [Key]
        public int ID { get; set; }
        public int IDProdotto { get; set; }
        public int IDOrdine { get; set; }
        public int Quantita { get; set; }

        [ForeignKey("IDOrdine")]
        [InverseProperty("Ordiniprodottis")]
        public virtual Ordine IDOrdineNavigation { get; set; }
        [ForeignKey("IDProdotto")]
        [InverseProperty("Ordiniprodottis")]
        public virtual Prodotto IDProdottoNavigation { get; set; }
    }
}