// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("Prodotto")]
    public partial class Prodotto
    {
        public Prodotto()
        {
            Ordiniprodottis = new HashSet<Ordiniprodotti>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }
        public int Quantita { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Prezzo { get; set; }
        [Column(TypeName = "image")]
        public byte[] Immagine { get; set; }
        public int Rating { get; set; }
        public int IDCategoria { get; set; }

        [ForeignKey("IDCategoria")]
        [System.Text.Json.Serialization.JsonIgnore]
        [InverseProperty("Prodottos")]
        public virtual Categoria IDCategoriaNavigation { get; set; }
        [InverseProperty("IDProdottoNavigation")]
        [System.Text.Json.Serialization.JsonIgnore]
        public virtual ICollection<Ordiniprodotti> Ordiniprodottis { get; set; }
    }
}